# Generated by Django 4.1 on 2022-09-16 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('option1', models.CharField(max_length=25)),
                ('option2', models.CharField(max_length=25)),
                ('option3', models.CharField(max_length=25)),
                ('option4', models.CharField(max_length=25)),
                ('answer', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='training',
            name='category',
        ),
        migrations.RemoveField(
            model_name='training',
            name='description',
        ),
        migrations.RemoveField(
            model_name='training',
            name='title',
        ),
        migrations.RemoveField(
            model_name='training',
            name='training_link',
        ),
        migrations.AddField(
            model_name='training',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='training',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(to='api.quizquestion')),
                ('topics', models.ManyToManyField(to='api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('training', models.ManyToManyField(to='api.training')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='topics',
            field=models.ManyToManyField(to='api.topic'),
        ),
    ]
