# Generated by Django 4.1 on 2022-09-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_quiz_topics_remove_training_topics_quiz_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='topics',
            field=models.ManyToManyField(to='api.topic'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='answer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
