# Generated by Django 4.1 on 2022-09-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_training_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='topics',
        ),
    ]
